const jCategory = [
  {
    index: 0,
    image: "../images/google.png",
    title: "Web Developer",
    rate: "$900 - 1200/m",
    availability: "Full Time",
    companyName: "Google",
    location: "USA",
    vacancy: "01",
    hours: "50h / week",
    jobDesc: `
    It is long a establishment fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more -or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose(injected humour and the like).
    `,
    employment: "- Full Time",
    workPlace: "- Work from home",
    education: "- Bachelor degree in any Computer Science Course.",
    experience: "2 to 5 year(s)",
  },
  {
    index: 1,
    image: "../images/uber.png",
    title: "Freelancer",
    rate: "$900 - 1200/m",
    availability: "Freelancer",
    companyName: "Uber",
    location: "USA",
    vacancy: "04",
    hours: "40h / week",
    jobDesc: `
    It is long a establishment fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more -or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose(injected humour and the like).
    `,
    employment: "- Freelance",
    workPlace: "- Work from office",
    education: "- Degree in any Computer Science Course.",
    experience: "1 to 5 year(s)",
  },
  {
    index: 2,
    image: "../images/linkedin.png",
    title: "Business Associate",
    rate: "$900 - 1200/m",
    availability: "Part Time",
    companyName: "LinkedIn",
    location: "USA",
    vacancy: "06",
    hours: "40h / week",
    jobDesc: `
    It is long a establishment fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more -or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose(injected humour and the like).
    `,
    employment: "- Part Time",
    workPlace: "- Work from home",
    education: "- Degree in any Computer Science Course.",
    experience: "1 to 5 year(s)",
  },
  {
    index: 3,
    image: "../images/facebook.png",
    title: "Digital Marketing",
    rate: "$900 - 1200/m",
    availability: "Full Time",
    companyName: "Facebook",
    location: "USA",
    vacancy: "02",
    hours: "40h / week",
    jobDesc: `
    It is long a establishment fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more -or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose(injected humour and the like).
    `,
    employment: "- Full Time",
    workPlace: "- Work from home",
    education: "- Degree in any Computer Science Course.",
    experience: "1 to 5 year(s)",
  },
  {
    index: 4,
    image: "../images/yahoo.png",
    title: "User Experience",
    rate: "$900 - 1200/m",
    availability: "Part Time",
    companyName: "Yahoo",
    location: "USA",
    vacancy: "03",
    hours: "40h / week",
    jobDesc: `
    It is long a establishment fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more -or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose(injected humour and the like).
    `,
    employment: "- Part Time",
    workPlace: "- Work from home",
    education: "- Degree in any Computer Science Course.",
    experience: "1 to 5 year(s)",
  },
  {
    index: 5,
    image: "../images/apple.png",
    title: "Web Developer",
    rate: "$900 - 1200/m",
    availability: "Full Time",
    companyName: "Apple",
    location: "USA",
    vacancy: "01",
    hours: "40h / week",
    jobDesc: `
    It is long a establishment fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more -or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose(injected humour and the like).
    `,
    employment: "- Full Time",
    workPlace: "- Work from home",
    education: "- Degree in any Computer Science Course.",
    experience: "2 to 5 year(s)",
  },
  {
    index: 6,
    image: "../images/instagram.png",
    title: "Product Designer",
    rate: "$900 - 1200/m",
    availability: "Part Time",
    companyName: "Meta",
    location: "USA",
    vacancy: "02",
    hours: "40h / week",
    jobDesc: `
    It is long a establishment fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more -or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose(injected humour and the like).
    `,
    employment: "- Part Time",
    workPlace: "- Work from home",
    education: "- Degree in any Computer Science Course.",
    experience: "2 to 5 year(s)",
  },
  {
    index: 7,
    image: "../images/wordpress.png",
    title: "Freelancer",
    rate: "$900 - 1200/m",
    availability: "Full Time",
    companyName: "Wordpress",
    location: "USA",
    vacancy: "03",
    hours: "40h / week",
    jobDesc: `
    It is long a establishment fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more -or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose(injected humour and the like).
    `,
    employment: "- Freelancer",
    workPlace: "- Work from home",
    education: "- Degree in any Computer Science Course.",
    experience: "2 to 5 year(s)",
  },
];